# pre-commit hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: check-json
  - id: check-ast
  - id: trailing-whitespace
  - id: end-of-file-fixer

# trailing comma fixer
- repo: https://github.com/asottile/add-trailing-comma
  rev: v4.0.0
  hooks:
  - id: add-trailing-comma

# yaml formatter
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2', --preserve-quotes]

# import cleaner
- repo: https://github.com/hadialqattan/pycln
  rev: v2.6.0
  hooks:
  - id: pycln
    args: [--config, pyproject.toml]

# import sorter
- repo: https://github.com/timothycrosley/isort
  rev: 7.0.0
  hooks:
  - id: isort
    files: \.(py)$
    args: [--settings-path, pyproject.toml]

# ruff
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.14.7'
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format

# static type checker
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.19.0
  hooks:
  - id: mypy
    args: [--config-file, pyproject.toml]

# exclude given directories from checking
exclude: |
  (?x)(
      ^src/temp/
  )
